### ISSUE TITLE
Google login fails, error: "popup_closed_by_user"

### ISSUE THREAD

**Issue by Navjot-Sharma** [hwasiti/Android_Popup_Webview_handler_example#3]
Thanks for the great work.

I'm facing an issue in google signin. Even though google login process starts on overriding user agent string. But when the login process completes, dialogue box closes but window doesn't redirects or any kind of reloading doesn't happen. This only happens in case of google login(facebook & linkedin logins are working fine).

On debugging in Chrome inspect tools, it shows error: "popup_closed_by_user"

On closing the app and opening it again, login process completes smoothly without even opening the dialogue box.

**Comment by Navjot-Sharma** [comment]
Hi,

If you are still maintaining this project
Just add this function in your MainActivity.java

`
private void enableHTML5AppCache(WebView mWebView) {

        mWebView.getSettings().setDomStorageEnabled(true);

        // Set cache size to 8 mb by default. should be more than enough
        mWebView.getSettings().setAppCacheMaxSize(1024 * 1024 * 8);

        mWebView.getSettings().setAppCachePath("/data/data/" + MainActivity.this.getPackageName() + "/cache");
        mWebView.getSettings().setAllowFileAccess(true);
        mWebView.getSettings().setAppCacheEnabled(true);

        mWebView.getSettings().setCacheMode(WebSettings.LOAD_DEFAULT);
    }`

And call this function when you set mWebview and mWebviewPop settings using getSettings() and login will work.

Thank you

**Comment by hwasiti** [comment]
Hi Navjot,

I will definitely try your suggestion once I get some time.

Thanks!
